services:
  - type: web
    name: fastapi-openrouter
    runtime: python
    region: singapore   # closest & fastest for India
    plan: free

    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn llm_api:app --host 0.0.0.0 --port $PORT

    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
